ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Config.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using ElGordo.App.Dominio;
using ElGordo.App.Persistencia;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;


namespace ElGrodo.App.Frontend.Pages
{
    [Authorize]
    public class ConfigModel : PageModel
    {
        private readonly IRepositorioEstadoProducto _repEstadoProducto;
        private readonly IRepositorioEstadoPedido _repEstadoPedido;
        private readonly IRepositorioEstadoFactura _repEstadoFactura;
        public IEnumerable<EstadoProducto> estadosProducto;
        public IEnumerable<EstadoPedido> estadosPedido;
        public IEnumerable<EstadoFactura> estadosFactura;
        
        [BindProperty]
        public EstadoProducto EstadoProducto { get; set; }
        [BindProperty]
        public EstadoPedido EstadoPedido { get; set; }
        [BindProperty]
        public EstadoFactura EstadoFactura{ get; set; }

        public ConfigModel()
        {
            this._repEstadoProducto = new RepositorioEstadoProducto(new ElGordo.App.Persistencia.AppContext());
            this._repEstadoPedido = new RepositorioEstadoPedido(new ElGordo.App.Persistencia.AppContext());
            this._repEstadoFactura = new RepositorioEstadoFactura(new ElGordo.App.Persistencia.AppContext());
            this.estadosProducto = _repEstadoProducto.GetAllEstadosProducto();
            this.estadosPedido = _repEstadoPedido.GetAllEstadosPedido();
            this.estadosFactura = _repEstadoFactura.GetAllEstadosFactura();
        }
        public void OnGet()
        {
            //Se inician los objetos en Blanco
            EstadoProducto = new EstadoProducto{};
            EstadoPedido = new EstadoPedido{};
            EstadoFactura = new EstadoFactura{};
        }

        public IActionResult OnPostNuevo()
        {
            ViewData["Respuesta"] = Alerts.ShowAlert(Alert.Primary, "<span><strong>"+Request.Form["estado"]+"</strong> fue agregado a la lista de Estados.</span>");
            return Page();
        }
        public IActionResult OnPostEditar()
        {
            ViewData["Respuesta"] = Alerts.ShowAlert(Alert.Success, "<span><strong>"+Request.Form["estado"]+"</strong> se actualizó correctamente.</span>");
            return Page();
        }
        public IActionResult OnPostEliminar()
        {
            ViewData["Respuesta"] = Alerts.ShowAlert(Alert.Danger, "<span><strong>"+Request.Form["estadoSelect"]+"</strong> se eliminó de la lista.</span>");
            return Page();
        }
    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ElGordo.App.Dominio;
using ElGordo.App.Persistencia;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ElGrodo.App.Frontend.Pages
{
    [Authorize]
    public class IndexAdminModel : PageModel
    {
        public IRepositorioPedido _repoPedidos;
        public IRepositorioEstadoPedido _repoEstadoPedidos;
        public IRepositorioFactura _repoFactura;
        public IRepositorioProductos _repoProducto;
        public IEnumerable<Pedido> Pedidos { get; set; }
        public IEnumerable<EstadoPedido> EstadoPedidos { get; set; }
        public string Marcadores { get; set; }

        public IndexAdminModel()
        {
            this._repoPedidos = new RepositorioPedido(new ElGordo.App.Persistencia.AppContext());
            this._repoEstadoPedidos = new RepositorioEstadoPedido(new ElGordo.App.Persistencia.AppContext());
            this._repoFactura = new RepositorioFactura(new ElGordo.App.Persistencia.AppContext());
            this._repoProducto = new RepositorioProductos(new ElGordo.App.Persistencia.AppContext());
        }

        public void OnGet()
        {
            CargaPagina();
        }       

        //=============================================================================
        //Carga el tipo de pedidos dependiendo de la opción seleccinada.
        public void CargaPagina()
        {
            //Si no se ha seleccionado ningun tipo de pedido se selecciona "Todos" por defecto
            var listaEstado = HttpContext.Session.GetInt32("lista") ?? 0;
            ViewData["listar"] = listaEstado;
            //Si no se ha asignado un tipo de pedidos, se muestran todos los pedidos pendientes para entregar
            //De lo contrario busca los pedidos por estado.
            Pedidos = (listaEstado == 0)?_repoPedidos.GetPendientes():_repoPedidos.GetPedidoPorEstado(listaEstado);
            //Obtiene los estados de pedido.
            EstadoPedidos = _repoEstadoPedidos.GetAllEstadosPedido();
            //Llama a la función RecorrerPedidos que se encarga 
            Marcadores = RecorrerPedidos();
            //Envía los marcadores del mapa a la vista.
            ViewData["marcadores"] = Marcadores;
        }

        //======================================================================================
        //Recorre la lista de pedidos y agrega las coordenadas e información necesaria para mostrar los marcadores en el mapa
        public string RecorrerPedidos()
        {
            var datos = "";
            //Recorre cada pedido
            foreach (var pedido in Pedidos)
            {
                datos += "{coords: { lat: " + pedido.LatitudEntrega + ", lng: " + pedido.LongitudEntrega + " }, img: iconBase, con: '<h5>" + pedido.Cliente + "</h5>";
                //Recorre cada detalle en la Factura
                foreach (var item in _repoFactura.GetFactura(pedido.Factura).Detalles)
                {
                    //Obtiene cada producto
                    var producto = _repoProducto.GetProducto(item.Producto);
                    datos += "<p>"+producto.Nombre + " x " + item.Cantidad+"</p>";
                }
                datos += "'},";
            }
            return datos;
        }

        //=========================================================================================
        //Cambia la lista dependiedo del valor que esté seleccionado en el Option Select
        public IActionResult OnPostCambiaLista()
        {
            //Captura el tipo de pedido a mostrar y lo guarda en una variable de sesión
            HttpContext.Session.SetInt32("lista", int.Parse(Request.Form["listaEstado"]));
            CargaPagina();
            return RedirectToPage("/Admin/Index");
        }

        //==========================================================================================
        //Captura el ID del pedido y cambia el estado sumando 1 al estado acutal
        public IActionResult OnPostCambiaEstado()
        {            
            var pedido = _repoPedidos.GetPedido(int.Parse(Request.Form["idpedido"]));//Captura el id del pedido
            _repoPedidos.UpdateEstadoPedido(pedido.Id); //Realiza el update del estado del pedido sumando 1 al estado actual
            CargaPagina();
            return RedirectToPage("/Admin/Index");
        }
        
        //===========================================================================================
        //Función para buscar un pedido en concreto... NO implementado
        //TODO
        public IActionResult OnPostBusca()
        {
            return RedirectToPage("/Admin/Index");
        }
    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Informes.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ElGordo.App.Dominio;
using ElGordo.App.Persistencia;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ElGrodo.App.Frontend.Pages
{
    [Authorize]
    public class InformesModel : PageModel
    {
        private readonly IRepositorioPedido _repoPedidos;
        public IRepositorioProductos _repoProroductos;
        public IRepositorioFactura _repoFactura;
        public IEnumerable<Pedido> Pedidos { get; set; }

        public InformesModel()
        {
            this._repoPedidos = new RepositorioPedido(new ElGordo.App.Persistencia.AppContext());
            this._repoProroductos = new RepositorioProductos(new ElGordo.App.Persistencia.AppContext());
            this._repoFactura = new RepositorioFactura(new ElGordo.App.Persistencia.AppContext());
        }
        public void OnGet()
        {
            Pedidos = _repoPedidos.GetAll();
        }
        public IActionResult OnPost()
        {
            // ViewData["fechamin"] = Request.Form["fechamin"];
            // ViewData["fechamax"] = Request.Form["fechamax"];
            // Console.WriteLine(Request.Form["fechamin"]+" "+Request.Form["fechamax"]);
            // Pedidos = _repoPedidos.GetAll();
            return Page();
        }
    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/ListaProductos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ElGordo.App.Dominio;
using ElGordo.App.Persistencia;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ElGrodo.App.Frontend.Pages
{
    [Authorize]
    public class ListaProductosModel : PageModel
    {
        private readonly IRepositorioProductos _repProducto;
        public IEnumerable<Producto> Productos { get; set; }

        public ListaProductosModel()
        {
            this._repProducto = new RepositorioProductos(new ElGordo.App.Persistencia.AppContext());
            this.Productos = _repProducto.GetAll();            
        }

        public void OnGet()
        {
            Productos = _repProducto.GetAll();
        }

        public void OnPost(int productoId, int estadoId)
        {
            if (estadoId == 1)
            {
                _repProducto.CambiaEstado(productoId, 2);
            }
            else
            {
                _repProducto.CambiaEstado(productoId, 1);
            }
        }

    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ElGordo.App.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authentication;
using ElGordo.App.Dominio;
using System.ComponentModel.DataAnnotations;

namespace ElGrodo.App.Frontend.Pages
{
    public class LoginModel : PageModel
    {
        private readonly IRepositorioUsuario _repUsuario;

        public LoginModel()
        {
            this._repUsuario = new RepositorioUsuario(new ElGordo.App.Persistencia.AppContext());
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string usuario,string password)
        {
            //Valida si los campos introducidos son correctos
            if(!ModelState.IsValid) return Page();
            var login = _repUsuario.Login(usuario,password);
            if(login!=null)
            {
                var claims = new List<Claim>{
                    new Claim(ClaimTypes.Name, "admin")
                };
                //Crea una cookie para mantener la sesión
                var identity = new ClaimsIdentity(claims, "CookieAdmin");
                ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync("CookieAdmin",claimsPrincipal).ConfigureAwait(false);
                return RedirectToPage("/Admin/Index");
            }
            //Devuelve el mensaje de error
            ViewData["Respuesta"] = Alerts.ShowAlert(Alert.Danger, "<span class='small'>Usuario o Contraseña incorrectos</span>");
            return Page();
        }
    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ElGrodo.App.Frontend.Pages
{
    [Authorize]
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnPostAsync()
        {
            await HttpContext.SignOutAsync("CookieAdmin").ConfigureAwait(false);
            return RedirectToPage("/Admin/Index");
        }

        public async Task<IActionResult> OnGet()
        {
            await HttpContext.SignOutAsync("CookieAdmin").ConfigureAwait(false);
            return RedirectToPage("/Admin/Index");
        }
    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Producto.cshtml.cs
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Linq;
using System.Threading.Tasks;
using ElGordo.App.Dominio;
using ElGordo.App.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;

namespace ElGrodo.Frontend.Pages
{
    [Authorize]
    public class ProductoModel : PageModel
    {
        private readonly IWebHostEnvironment _enviroment;
        private readonly IRepositorioProductos _repProducto;
        private readonly IRepositorioEstadoProducto _repEstadoProducto;
        [BindProperty]
        public Producto Producto { get; set; }
        [BindProperty]
        public IFormFile Imagen { get; set; }
        public IEnumerable<EstadoProducto> estadosProducto;
        public ProductoModel(IWebHostEnvironment environment)
        {
            _enviroment = environment;
            this._repProducto  = new RepositorioProductos(new ElGordo.App.Persistencia.AppContext());
            this._repEstadoProducto = new RepositorioEstadoProducto(new ElGordo.App.Persistencia.AppContext());
            this.estadosProducto = _repEstadoProducto.GetAllEstadosProducto();
        }
        public IActionResult OnGet(int? productoId)
        {
            //Si el productoId que llega por GET tiene un valor
            if (productoId.HasValue)
            {
                //Busca el producto en la base de datos
                Producto = _repProducto.GetProducto(productoId.Value);
            }
            else
            {
                //Crea un nuevo producto y agrega valores por defecto
                Producto = new Producto { Estado = 1, Imagen = "default.png" };
            }

            //Si envian un Id de producto que no está en la base de datos
            if (Producto == null)
            {
                //Devuelve la pagina de error
                return Redirect("/Errors/404");
            }
            else
            {
                return Page();
            }
        }

        public async Task<IActionResult> OnPost(int estado)//Estado es el nombre del Select estados.
        {
            Producto.Estado = estado;
            //Console.WriteLine(JsonSerializer.Serialize(Producto));
            if (!ModelState.IsValid) { return Page(); }
            
            if (Imagen != null)
            {//Si se ha seleccionado una imagen la sube a la carpeta "wwwroot\img"
            // Producto.Imagen = Imagen.FileName;
                var imgUpload = System.IO.Path.Combine(_enviroment.ContentRootPath, "wwwroot\\img", Imagen.FileName);
                await Imagen.CopyToAsync(new System.IO.FileStream(imgUpload, System.IO.FileMode.Create));
            }
            if (Producto.Id > 0)
            {
                //Si el Id del producto es mayor que cero actualizar el Producto enviado
                Producto = _repProducto.UpdateProducto(Producto);
                ViewData["Respuesta"] = Alerts.ShowAlert(Alert.Success, "<span>" + Producto.Nombre + " fue modificado correctamente</span>");
            }
            else
            {
                //Si el Id del Prodcuto es CERO crea un nuevo producto
                _repProducto.AddProducto(Producto);
                ViewData["Respuesta"] = Alerts.ShowAlert(Alert.Primary, "<span><strong>" + Producto.Nombre + "</strong> se agregó a la lista de productos</span>");
            }

            return Page();
        }
    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Config.cshtml
@page
@model ElGrodo.App.Frontend.Pages.ConfigModel
@{
    ViewData["Title"] = "Pedidos";
}
<div class="row d-flex justify-content-center">
    <div class="col-6">
        @Html.Raw(@ViewData["Respuesta"])
    </div>    
</div>
<div class="d-flex justify-content-center">
    <h3 class="text-muted my-4">SECCIÓN NO DISPONIBLE</h3>
</div>
<div class="d-flex justify-content-center">    
    <div class="border rounded p-4 m-4">
        <h5 class="mb-4">Estados Pedido</h5>
        <select class="form-control mb-4" name="estadoSelect" id="selectEstado">
            @foreach (var item in Model.estadosPedido)
            {
                <option value="@item.Id">@item.Nombre</option>
            }
        </select>
        <form class="" method="POST">
            <input type="hidden" asp-for="EstadoPedido.Id" />
            <div class="form-group">
                <input asp-for="EstadoPedido.Nombre" class="form-control" name="estado">
                <span asp-validation-for="EstadoPedido.Nombre" class="text-danger"></span>
            </div>
            <div>
                <button type="submit" class="btn btn-outline-primary mr-2" asp-page-handler="Nuevo">Nuevo</button>
                <button type="submit" class="btn btn-outline-primary mr-2" asp-page-handler="Editar">Editar</button>
                <button type="submit" class="btn btn-outline-danger" asp-page-handler="Eliminar">Eliminar</button>
            </div>
        </form>
    </div>

    <div class="border rounded p-4 m-4">
        <h5 class="mb-4">Estados Producto</h5>
        <select class="form-control mb-4" name="estadoSelect" id="selectEstado">
            @foreach (var item in Model.estadosProducto)
            {
                <option value="@item.Id">@item.Nombre</option>
            }
        </select>
        <form class="" method="POST">
            <input type="hidden" asp-for="EstadoProducto.Id" />
            <div class="form-group">
                <input asp-for="EstadoProducto.Nombre" class="form-control" name="estado">
                <span asp-validation-for="EstadoProducto.Nombre" class="text-danger"></span>
            </div>
            <div>
                <button type="submit" class="btn btn-outline-primary mr-2" asp-page-handler="Nuevo">Nuevo</button>
                <button type="submit" class="btn btn-outline-primary mr-2" asp-page-handler="Editar">Editar</button>
                <button type="submit" class="btn btn-outline-danger" asp-page-handler="Eliminar">Eliminar</button>
            </div>
        </form>
    </div>

    <div class="border rounded p-4 m-4">
        <h5 class="mb-4">Estados Factura</h5>
        <select class="form-control mb-4" name="estadoSelect" id="selectEstado">
            @foreach (var item in Model.estadosFactura)
            {
                <option value="@item.Id">@item.Nombre</option>
            }
        </select>
        <form class="" method="POST">
            <input type="hidden" asp-for="EstadoFactura.Id" />
            <div class="form-group">
                <input asp-for="EstadoFactura.Nombre" class="form-control" name="estado">
                <span asp-validation-for="EstadoFactura.Nombre" class="text-danger"></span>
            </div>
            <div>
                <button type="submit" class="btn btn-outline-primary mr-2" asp-page-handler="Nuevo">Nuevo</button>
                <button type="submit" class="btn btn-outline-primary mr-2" asp-page-handler="Editar">Editar</button>
                <button type="submit" class="btn btn-outline-danger" asp-page-handler="Eliminar">Eliminar</button>
            </div>
        </form>
    </div>    
</div>

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Index.cshtml
@page
@using System.Globalization
@model ElGrodo.App.Frontend.Pages.IndexAdminModel
@{
    ViewData["Title"] = "Pedidos";
    var total = 0.0;
    var estado = new List<string>();
}
<div class="row">
    <div class="col-5">
        <div class="row">
            <div class="col-5 pr-0">
                <form class="mb-4" method="post" asp-page-handler="CambiaLista">
                    <input type="hidden" name="cambia" value="preparacion">
                    <select class="form-control" name="listaEstado" id="selectlista" onchange="this.form.submit()">
                        <option value="0">Todos</option>
                        @foreach (var item in Model.EstadoPedidos)
                        {
                            <option value="@item.Id">@item.Nombre</option>
                        }
                    </select>
                </form>
            </div>
            <div class="col-7 pl-0">
                @* Botón para hacer busquedas.. NO implementado
                <form class="form-inline justify-content-end" asp-page-handler="Busca">
                    <input class="form-control mr-sm-2 col-sm-7" type="search" placeholder="Código" name="codigo">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Buscar</button>
                    </form> *@
            </div>
        </div>

        @* Tabla que muestra la lista de pedidos enocontrados en la base de datos *@
        <div id="accordion">
            @foreach (var pedido in Model.Pedidos)
            {
                total = 0;
                var idDiv = "div" + pedido.Id;
                @switch (pedido.Estado)
                {
                    case 1:
                        estado = new List<string>(){"danger","Realizado","warning","Pasar a Preparación","<button class='btn btn-secondary mt-3'>Imprimir Orden</button>"};
                        break;
                    case 2:
                        estado = new List<string>() { "warning", "Preparación","primary","Enviar",""};
                        break;
                    case 3:
                        estado = new List<string>() { "primary", "Enviado","success","Entregado",""};
                        break;
                    default:
                        estado = new List<string>() { "success", "Entregado","","",""};
                        break;
                }
                <div class="card">
                    <div class="card-header p-0" id="headingOne">
                        <a class="collapsed text-decoration-none d-flex justify-content-between" href="#"
                        data-toggle="collapse" data-target="#@idDiv">
                        <div class="p-2 d-flex">
                            <span class="text-dark p-0 small" style="width:80px;"><strong>@pedido.Fecha_pedido.ToString("h:mm tt")</strong></span>
                            <span class="text-dark">@pedido.Cliente</span>
                        </div>
                            
                            <div class="p-2 small"><strong class="text-@estado[0]">@estado[1]</strong></div>
                        </a>
                    </div>
                    <div id="@idDiv" class="collapse" data-parent="#accordion">
                        <div class="card-body">
                            <ul class="list-group">
                                @* Obtiene todos los detalles de cada pedido *@
                                @foreach (var item in @Model._repoFactura.GetFactura(pedido.Factura).Detalles)
                                {
                                    @* Obtiene el producto relacionado al detalle de la factura *@
                                    var producto = @Model._repoProducto.GetProducto(item.Producto);
                                    <li class="list-group-item p-1 d-flex justify-content-between"><span>@producto.Nombre x
                                            @item.Cantidad</span><span>$@((item.Cantidad*item.Precio).ToString("0,0",new CultureInfo("es-AR")))</span></li>
                                    total += item.Cantidad * item.Precio;
                                }
                                <li class="list-group-item font-weight-bold p-1 d-flex justify-content-end">Total:
                                    $@total.ToString("0,0",new CultureInfo("es-AR"))</li>
                                <li class='list-group-item font-weight-bold p-1 text-success'>Notas: @pedido.Notas</li>
                                <li class="list-group-item font-weight-bold p-1 small">Codigo: @pedido.Codigo</li>
                            </ul>
                            <div class="d-flex justify-content-between">
                                @Html.Raw(@estado[4])
                                <form class="form-inline justify-content-end col px-0" method="POST">
                                    <input type="hidden" name="listaestado" value="@Html.Raw(@ViewData["listar"])">
                                    <input type="hidden" name="idpedido" value="@pedido.Id">
                                    <button class="btn btn-@estado[2] form-group mt-4" type="submit" asp-page-handler="CambiaEstado">@estado[3]</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <!-- Fin lista pedidos -->
    </div>
    <div class="col-7">
        <div id="map" style="min-height: 600px;resize: both;" class=""></div>
        <script
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtbBQFARnVwieOQDfyR2vDN8B1xdXWBfk&callback=initMap&libraries=&v=weekly"
            async></script>
        <!-- Script encargado de procesar los datos del mapa -->
        <script>
            function initMap() {
                var options = {
                    zoom: 6, map, center: { lat: 4.570868, lng: -74.297333 }
                }
                var map = new google.maps.Map(document.getElementById('map'), options);
                var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/parking_lot_maps.png';
                var markers = [@Html.Raw(@ViewData["marcadores"])];//Se obtienen los marcadores del mapa
                for (var i = 0; i < markers.length; i++) {
                    addMarker(markers[i]);
                }
                function addMarker(info) {
                    var marker = new google.maps.Marker({
                        position: info.coords,
                        map: map,
                    });
                    var infoWindow = new google.maps.InfoWindow({
                        content: info.con,
                    });
                    marker.addListener('mouseover', () => {
                        infoWindow.open(map, marker);
                    });
                    marker.addListener('mouseout', () => {
                        infoWindow.close(map, marker);
                    });
                }
            }
            
            //Selecciona el item actual en la lista de Estados de Pedido
            document.getElementById("selectlista").value = @Html.Raw(@ViewData["listar"]);

        </script>
    </div>
</div>

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/ListaProductos.cshtml
@page
@using System.Globalization
@model ElGrodo.App.Frontend.Pages.ListaProductosModel
@{
    ViewData["Title"] = "Productos";
}
<h4 class="mb-4">Lista de productos</h4>
<a asp-page="./Producto" class="btn btn-primary mb-3">Nuevo Producto</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nombre</th>
            <th scope="col">Imagen</th>
            <th scope="col">Precio</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Producto in Model.Productos)
        {
            <tr>
                <th scope="row">@Producto.Id</th>
                <td>@Producto.Nombre</td>
                <td>
                    <img src="~/img/@Producto.Imagen" alt="" class="img-thumbnail img-fluid" width="100px"
                    max-height="150px" ;>
                </td>
                <td>$ @Producto.Precio.ToString("0,0",new CultureInfo("es-AR"))</td>
                <td>
                    <form method="POST" id="@Producto.Id" class="form-inline">
                        <a class="btn btn-success mr-2" asp-page="./Producto" data-toggle="tooltip" data-placement="left" title="Editar" asp-route-ProductoId="@Producto.Id">
                            <i class="fas fa-edit" aria-hidden="true"></i>
                        </a>
                        <input type="hidden" value="@Producto.Id" name="productoId" >
                        <input type="hidden" value="@Producto.Estado" name="estadoId">                    
                    @{
                        if (Producto.Estado == 1)
                        {
                            <a href="javascript:$('#@Producto.Id').submit();" class="btn btn-primary" data-toggle="tooltip" data-placement="right" title="Ocultar"><i
                            class="fas fa-eye"></i></a>
                        }
                        else if (Producto.Estado == 2)
                        {
                            <a href="javascript:$('#@Producto.Id').submit();" class="btn btn-danger" data-toggle="tooltip" data-placement="right" title="Mostrar"><i
                            class="fas fa-eye"></i></a>
                        }
                    }
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Login.cshtml
@page
@model ElGrodo.App.Frontend.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}
<div class="collapse navbar-collapse d-flex justify-content-center mt-5" id="navbarSupportedContent">    
    <div class="col-md-4 border rounded p-4 shadow-sm">
        <h4 class="mb-4 mt-3 text-primary">Iniciar Sesión</h4>
         @Html.Raw(@ViewData["Respuesta"])
        <form class="form col" method="POST">
            <div class="form-group row">
                <input name="usuario" class="form-control" placeholder="Usuario">
            </div>
            <div class="form-group row">
                <input type="password" name="password" class="form-control" placeholder="Contraseña">
            </div>
            <div class="form-group row">
                <button class="btn btn-primary" type="submit">Entrar</button>
            </div>
        </form>
    </div>
</div>

ElGordo.App/ElGordo.App.Frontend/Pages/Admin/Logout.cshtml
@page
@model ElGrodo.App.Frontend.Pages.LogoutModel
@{
}