ElGordo.App/ElGordo.App.Frontend/Pages/Pedido/CompletarPedido.cshtml.cs
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Linq;
using System.Threading.Tasks;
using ElGordo.App.Dominio;
using ElGordo.App.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace ElGrodo.App.Frontend.Pages
{
    public class CompletarPedidoModel : PageModel
    {
        [BindProperty]
        public Pedido Pedido{get;set;}
        public IActionResult OnGet()
        {
            return CargaDatos();
        }
        public IActionResult OnPost()
        {
            return CargaDatos();
        }

        //Al hacer clic en el boton Pagar captura los datos del pedido y los guarda en una variable de sesión
        public IActionResult OnPostHacerPedido()
        {
            if (!ModelState.IsValid) { return CargaDatos();}
            //Variable de sesión
            HttpContext.Session.SetString("pedido", JsonSerializer.Serialize(Pedido));
            return RedirectToPage("/Pedido/Pago");
        }

        public IActionResult CargaDatos()
        {
            //Comprueba que existan datos en la variable de sesión "carrito"
            if(HttpContext.Session.GetString("carrito") == null||HttpContext.Session.GetString("carrito") == "[]"){
                ViewData["JsonCarrito"] = "[]";
                return RedirectToPage("/Index");
            }else{
                ViewData["JsonCarrito"] = HttpContext.Session.GetString("carrito");
                return Page();
            } 
        }
    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Pedido/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ElGordo.App.Dominio;
using ElGordo.App.Persistencia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ElGrodo.App.Frontend.Pages
{
    public class IndexPedidoModel : PageModel
    {
        public IRepositorioPedido _repoPedido;
        public IRepositorioEstadoPedido _repoEstadoPedido;
        public IRepositorioFactura _repoFactura;
        public IRepositorioProductos _repoProducto;
        public Pedido Pedido{get;set;}
        public EstadoPedido EstadoPedido{get;set;}
        public Factura Factura{get;set;}

        //Constructor 
        public IndexPedidoModel()
        {
            this._repoPedido = new RepositorioPedido(new ElGordo.App.Persistencia.AppContext());
            this._repoEstadoPedido = new RepositorioEstadoPedido(new ElGordo.App.Persistencia.AppContext());
            this._repoFactura = new RepositorioFactura(new ElGordo.App.Persistencia.AppContext());
            this._repoProducto = new RepositorioProductos(new ElGordo.App.Persistencia.AppContext());
        }
        public void OnGet(string codigo)
        {
            //Verifica si se envió un código por GET (?codigo=xxx)
            if (codigo==null)
            {
                //Si no hay un código crea un objeto vacio
                Pedido = new Pedido{};                
            }
            else
            {
                //Busca el código en la Base de Datos
                Pedido = _repoPedido.GetPorCodigo(codigo);
                //Verifica si la base de datos devolvió un Pedido.
                if(Pedido==null){
                    //Si el código no es válido crea un objeto vacio y envía el mensaje de error a la vista.
                    Pedido = new Pedido{};
                    ViewData["Respuesta"] = Alerts.ShowAlert(Alert.Danger, "<span>El pedido <strong>"+codigo+"</strong> no existe</span>");                                        
                }else{
                    //Si hay un pedido válido se busca el estado del pedido.
                    EstadoPedido = _repoEstadoPedido.GetEstadoPedido(Pedido.Estado);
                    Factura = _repoFactura.GetFactura(Pedido.Factura);
                    ViewData["latitud"] = Pedido.LatitudEntrega;
                    ViewData["longitud"] = Pedido.LongitudEntrega;
                }
            }            
        }
    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Pedido/Pago.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using ElGordo.App.Dominio;
using Newtonsoft.Json;
using System.Text.Json;
using ElGordo.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace ElGrodo.App.Frontend.Pages
{
    public class PagoModel : PageModel
    {
        //Se agregan asignan los repositorios necesarios a variables para acceder a sus metodos
        public IRepositorioProductos _repoProducto;
        public IRepositorioPedido _repoPedido;
        public IRepositorioFactura _repoFactura;        
        public IRepositorioEstadoPedido _repoEstadoPedido;
        public IRepositorioEstadoFactura _repoEstadoFactura;
        
        //Se crean las lista y variables necesarias para generar los datos del pedido
        public List<Carrito> ListaCarrito { get; set; }
        public Pedido Pedido { get; set; }
        public Factura Factura{get;set;}
        public int Total { get; set; }
        public List<Detalle> ListaDetalles{get;set;}

        //Constructor
        public PagoModel(){
            this._repoProducto = new RepositorioProductos(new ElGordo.App.Persistencia.AppContext());
            this._repoPedido = new RepositorioPedido(new ElGordo.App.Persistencia.AppContext());
            this._repoFactura = new RepositorioFactura(new ElGordo.App.Persistencia.AppContext());
            this._repoEstadoPedido = new RepositorioEstadoPedido(new ElGordo.App.Persistencia.AppContext());
            this._repoEstadoFactura = new RepositorioEstadoFactura(new ElGordo.App.Persistencia.AppContext());
        }

        //Método principal que se ejecuta al cargar la Página.
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("carrito") == null || HttpContext.Session.GetString("carrito") == "[]"||HttpContext.Session.GetString("pedido") == null || HttpContext.Session.GetString("pedido") == "[]")
            {
                return RedirectToPage("/Index");//Si no existen las variables "carrito" o "pedido" se redirige a la pantalla principal.
            }   

            //Se convierte el string del carrito(Varaible de sesión) en una lista de Objetos tipo "Carrito"
            ListaCarrito = JsonConvert.DeserializeObject<List<Carrito>>(HttpContext.Session.GetString("carrito"));
            //Se convierte el string del pedido(Varaible de sesión) en un Objeto de tipo Pedido
            Pedido = JsonConvert.DeserializeObject<Pedido>(HttpContext.Session.GetString("pedido"));

            //Se eliminan las variables de sesión
            HttpContext.Session.Remove("carrito");
            HttpContext.Session.Remove("pedido");

            //Se asigna el estado del pedido a "Realizado" y se agrega la fecha y hora actual
            Pedido.Estado = 1;//Se asigna el estado como Realizado
            //Se asigna DateTime a todas las fechas para evitar valores nulos 
            Pedido.Fecha_pedido = DateTime.Now;
            Pedido.Fecha_preparacion = DateTime.Now;
            Pedido.Fecha_envio = DateTime.Now;
            Pedido.Fecha_entrega = DateTime.Now;

            //Se ejecuta la función encargada de guardar los datos en la BD 
            GuardaDatosBD();      

            //Se envian los Ojetos a la vista.
            ViewData["JsonCarrito"] = System.Text.Json.JsonSerializer.Serialize(ListaCarrito);
            ViewData["JsonPedido"] = System.Text.Json.JsonSerializer.Serialize(Pedido);
            return Page();
        }

        //Funcion que guarda todo en la Base de Datos.
        public void GuardaDatosBD()
        {
            //Se ejecuta la función que generar los detalles y la factura
            GenerarFactura();
            Factura FacturaBD = _repoFactura.AddFactura(Factura); 
            if(FacturaBD!=null){
                Pedido.Factura= FacturaBD.Id; 
            }
            Pedido = _repoPedido.AddPedido(Pedido); 
        }

        //Funcion que genera la factura, Recorre la lista del carrito 
        //genera los Detalles para enviarlos a la base de datos 
        public void GenerarFactura()
        {
            ListaDetalles = new List<Detalle>();
            Total = 0;
            foreach (var item in ListaCarrito)
            {
                var newDetalle = new Detalle{
                    Producto = item.Id,
                    Precio = _repoProducto.GetProducto(item.Id).Precio,
                    Cantidad = item.Cantidad
                };                    
                ListaDetalles.Add(newDetalle);//Se agrega un detalle a lista por cada item de la "ListaCarrito"
                Total += item.Precio * item.Cantidad;//Se calcula el Total de la factura.
            }
            //Se asignan los atributos a la Factura
            Factura = new Factura{ 
                Estado = 1,
                Fecha = DateTime.Now,
                Detalles = ListaDetalles    
            };
        }        
    }
}

ElGordo.App/ElGordo.App.Frontend/Pages/Pedido/CompletarPedido.cshtml
@page
@model ElGrodo.App.Frontend.Pages.CompletarPedidoModel
@{
    ViewData["Title"] = "Detalles De Envío";
}
<div class="d-flex justify-content-center">
    <div class="text-center border rounded shadow col-lg-4 col-md-6 col-sm-8 col-xs-10 m-4 p-4"
        style="min-width:350px;">
        <h4 class="mb-4 text-primary">Datos de Envío</h4>
        <form class="mb-0 mx-4" method="POST" asp-page-handler="HacerPedido">
            <p id="af"></p>
            <input type="hidden" asp-for="Pedido.Id" />
            <input type="hidden" asp-for="Pedido.Codigo" />
            <div class="form-group">
                <input asp-for="Pedido.Cliente" class="form-control" placeholder="Nombre">
                <span asp-validation-for="Pedido.Cliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <!--Boton que llama el mapa-->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg"
                    onclick="cambiaCoordenadas();">Agregar Ubicación</button>
            </div>
            <div class="form-group">
                <input asp-for="Pedido.LatitudEntrega" class="form-control form-control-sm" id="latitudForm"
                    placeholder="Latitud" value="">
                <span asp-validation-for="Pedido.LatitudEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Pedido.LongitudEntrega" class="form-control form-control-sm" id="longitudForm"
                    placeholder="Longitud" value="">
                <span asp-validation-for="Pedido.LongitudEntrega" class="text-danger"></span>
            </div>
            <div class="form-group">
                <textarea asp-for="Pedido.Notas" class="form-control form-control-sm" style="min-height: 80px;"
                    placeholder="Espeficiar dirección, modificaciones de pedido, notas adicionales..."></textarea>
                <span asp-validation-for="Pedido.Notas" class="text-danger"></span>
            </div>
            <div class="justity-content-center">
                <ul class="list-group small" id="listaPagar">
                    <li class="list-group-item list-group-item-primary font-weight-bold p-1">Pedido</li>

                </ul>
            </div>
            <button type="submit" class="btn btn-primary mt-4">Pagar</button>
        </form>
    </div>
</div>
<partial name="_MapaDefinirUbicacion" />
<!--Agrega el modal del mapa-->

@section Scripts {
<script type="text/javascript">
    listaCancelar = @Html.Raw(@ViewData["JsonCarrito"]);
    let total = 0;
    listaCancelar.forEach(e => {
        $('#listaPagar').append('<li class="list-group-item list-group-item-primary p-1">' + e.item + ' x ' + e.cantidad + '</li>');
        total += e.precio * e.cantidad;
    });
    $('#listaPagar').append('<li class="list-group-item list-group-item-primary font-weight-bold p-1">Total: $' + moneda(total) + '</li>');

    //Funcion que genera el codigo aleatorio
    function codigoAleatorio() {
        let codigo = '';
        const lista = '0123456789abcdefghijklmnopqrstuvwxyz0123456789';
        const listaTam = lista.length;
        for (let i = 0; i < 8; i++) {
            codigo += lista.charAt(Math.floor(Math.random() * listaTam));
        }
        return codigo;
    }
    $('#Pedido_Codigo').val(codigoAleatorio());
</script>
}

ElGordo.App/ElGordo.App.Frontend/Pages/Pedido/Index.cshtml
@page
@using System.Globalization
@model ElGrodo.App.Frontend.Pages.IndexPedidoModel
@{
    ViewData["Title"] = "Pedido";
    var clock = "<i class='fas fa-clock text-success'></i>";
    var formato = "h:mm tt";
    var total = 0.0;
}

@if (Model.Pedido.Codigo == null)//Si no hay un código válido
{
    //Div que muestra el mensaje de error en caso de no encontrar un pedido
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            @Html.Raw(@ViewData["Respuesta"])
        </div>
    </div>
    //====================================================================
    <div class="d-flex justify-content-center col">
        <div class="text-center border rounded shadow col col-lg-4 col-md-6 col-sm-8 col-xs-10 m-4 p-4">
            <h4 class="mb-4 text-primary">Buscar Pedido</h4>
            <form class="form-inline my-lg-0 justify-content-center col" asp-page="/Pedido/Index" method="GET">
                <input class="form-control form-group" type="search" placeholder="Código" name="codigo">
                <button class="btn btn-primary form-group mt-4" type="submit">Rastrear</button>
            </form>
        </div>
    </div>
}
@* Si el código existe en la base de datos *@
else
{
    <div class="d-flex justify-content-center">
        <div class="text-center border rounded shadow col-lg-4 col-md-6 col-sm-8 col-xs-10 m-4 p-4">
            <h4 class="mb-4 text-success">Estado</h4>
            <div class="d-flex justify-content-center">
                <div class="alert alert-success col-6" role="alert">
                    <span class="font-weight-bold">@Model.EstadoPedido.Nombre</span>
                </div>
            </div>
            <p class="font-weight-bold">@Model.Pedido.Cliente</p>
            <div class="justity-content-center m-4">
                <ul class="list-group">
                    <li class="list-group-item font-weight-bold p-1">Historia</li>
                    <li class="list-group-item p-1">Realizado: @Model.Pedido.Fecha_pedido.ToString(formato)</li>
                    <li class="list-group-item p-1">Preparación:
                        @((Model.Pedido.Estado > 1
                    )?Html.Raw(((DateTime)Model.Pedido.Fecha_preparacion).ToString(formato)):Html.Raw(clock))
                    </li>
                    <li class="list-group-item p-1">Enviado:
                        @((Model.Pedido.Estado > 2
                    )?Html.Raw(((DateTime)Model.Pedido.Fecha_envio).ToString(formato)):Html.Raw(clock))
                    </li>
                    <li class="list-group-item p-1">Recibido:
                        @((Model.Pedido.Estado > 3
                    )?Html.Raw(((DateTime)Model.Pedido.Fecha_entrega).ToString(formato)):Html.Raw(clock))
                    </li>
                </ul>
            </div>
            <p class="small">Código: @Model.Pedido.Codigo</p>
            <!--Boton que llama el modal de Detalle-->
        <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target=".bd-example-modal-lg">Ver
                Detalles</button>
        </div>
    </div>
    <!-- Modal Detalles de la venta -->
    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="modalMapa" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="form-inline d-flex justify-content-end mb-3">
                        <div>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 pr-0">
                            <h4 class="mb-5 text-primary">@Model.Pedido.Cliente</h4>
                            <table class="table">
                                <thead>
                                    <tr class="">
                                        <th scope="col">Producto</th>
                                        <th scope="col">Precio</th>
                                        <th scope="col">Cant.</th>
                                        <th scope="col">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in @Model.Factura.Detalles)
                                    {
                                        var producto = @Model._repoProducto.GetProducto(item.Producto);
                                        total += item.Cantidad * item.Precio;
                                        <tr>
                                            <td>@producto.Nombre</td>
                                            <td>$@item.Precio.ToString("0,0",new CultureInfo("es-AR"))</td>
                                            <td>@item.Cantidad</td>
                                            <td>$@((item.Cantidad*item.Precio).ToString("0,0",new CultureInfo("es-AR")))</td>
                                        </tr>
                                    }
                                    <tr class="text-primary">
                                        <th scope="col"></th>
                                        <th scope="col"></th>
                                        <th scope="col"><strong>Total:</strong></th>
                                        <th scope="col">$@total.ToString("0,0",new CultureInfo("es-AR"))</th>
                                    </tr>
                                </tbody>
                            </table>
                            <div class="text-secondary small">
                                <strong>Notas:</strong>
                                <p>@Model.Pedido.Notas</p>
                            </div>
                        </div>
                        <div class="col-md-6 px-3">
                            <div id="map" style="height: 500px;" class="border rounded"></div>
                        </div>
                    </div>
                    <div class="mt-3">
                        <div class="form-inline d-flex justify-content-end">
                            <div>
                                <button type="button" class="btn btn-primary ml-4" data-dismiss="modal">Aceptar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtbBQFARnVwieOQDfyR2vDN8B1xdXWBfk&callback=initMap&libraries=&v=weekly"
    async></script>

    <script>
        function initMap() {
            coordenadas = { lat: @Html.Raw(@ViewData["latitud"]), lng: @Html.Raw(@ViewData["longitud"]) }
            generarMapa(coordenadas);
        }
        function generarMapa(coordenadas) {
            var mapa = new google.maps.Map(document.getElementById('map'),
                {
                    zoom: 10,
                    center: new google.maps.LatLng(coordenadas.lat, coordenadas.lng)
                });
            posicion = new google.maps.Marker({
                map: mapa,
                position: new google.maps.LatLng(coordenadas.lat, coordenadas.lng)
            });
        }
    </script>
}

ElGordo.App/ElGordo.App.Frontend/Pages/Pedido/Pago.cshtml
@page
@using System.Globalization
@model ElGrodo.App.Frontend.Pages.PagoModel
@{
    ViewData["Title"] = "Pedido";
}
<div class="d-flex justify-content-center">
    <div class="text-center border rounded shadow col-lg-4 col-md-6 col-sm-8 col-xs-10 m-4 p-4">
        <div class="d-flex justify-content-center">
            <div class="alert alert-success col-8" role="alert">
                <p class="alert-heading font-weight-bold">Pago Aprobado</p>
                <i class="fas fa-check h5"></i>
            </div>
        </div>        
        <div class="justity-content-center m-4">
            <ul class="list-group small">
                <li class="list-group-item font-weight-bold p-1">@Model.Pedido.Cliente</li>
                <li class="list-group-item p-1">Fecha: @Model.Pedido.Fecha_pedido</li>
                <li class="list-group-item p-1">Código de Transacción: 453123572654</li>
                <li class="list-group-item font-weight-bold p-1">Total: $@Model.Total.ToString("0,0",new CultureInfo("es-AR"))</li>
            </ul>
        </div>
        <div class="m-4">
            <div class="alert alert-primary" role="alert">
                <p class="font-weight-bold">Código de seguimiento</p>
                <p class="h3 font-weight-normal">@Model.Pedido.Codigo</p>
            </div>
        </div>
        <a title="Ver detalles" class="btn btn-success" asp-page="./Index/" asp-route-codigo="@Model.Pedido.Codigo">Ver Pedido</a>
    </div>
</div>